### ISSUE TITLE
SuperSortD.cppのalignについて

### ISSUE THREAD

**Issue by yaneurao** [TokusiN/SuperSort#1]
https://github.com/TokusiN/SuperSort/blob/69db57fbc87b94950477386f0992668dfd8d851c/SuperSortD.cpp#L33

なのですが、32バイトでalignされているかを判定しているならば
> bool isAligned = (((size_t)arr) & 31) == 0;
が正しいコードではないでしょうか。

https://github.com/TokusiN/SuperSort/blob/69db57fbc87b94950477386f0992668dfd8d851c/SuperSortD.cpp#L41

ソート対象の要素数を16の倍数になるように繰り上げてあるのだと思うのですが、

> alignedsize = (num + 15) & ~15;

と書いたほうが演算回数が1回少なく、明快なコードであるように思います。

**Comment by TokusiN** [comment]
alignチェックが間違っている件は、Qhapaqに組み込んだ時に発覚して修正したのですが、
こちらでは修正していませんでした。
他にもmallocを省略するためにグローバル変数を使ってしまっているのでマルチスレッド非対応だったり、
色々と不具合を直しているのでそちらのバージョンに更新します。
alignedsizeの計算が1命令減るのは単純に見落としていました。

**Comment by yaneurao** [comment]
承知しました(｀･ω･´)ゞ
素晴らしいライブラリをありがとうございます。
